const crypto = require('node:crypto');
const path = require('node:path');
const express = require('express');
const mysql = require('mysql2/promise');

const app = express();
const port = Number(process.env.PORT || 3000);
const sessionDays = Math.max(1, Number(process.env.SESSION_DAYS || 30));
const secureCookies = process.env.SECURE_COOKIES === 'true';
const loginWindowMs = 15 * 60 * 1000;
const loginAttempts = new Map();
const pool = mysql.createPool({ host: process.env.DB_HOST || 'db', port: Number(process.env.DB_PORT || 3306), user: process.env.DB_USER || 'formkurva', password: process.env.DB_PASSWORD || '', database: process.env.DB_NAME || 'formkurva', waitForConnections: true, connectionLimit: 10, charset: 'utf8mb4' });

async function initDatabase() {
  await pool.query(`CREATE TABLE IF NOT EXISTS users (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, email VARCHAR(254) NOT NULL UNIQUE, password_hash CHAR(128) NOT NULL, password_salt CHAR(32) NOT NULL, role ENUM('admin','user') NOT NULL DEFAULT 'user', profile_json LONGTEXT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB`);
  await pool.query(`CREATE TABLE IF NOT EXISTS sessions (id CHAR(64) PRIMARY KEY, user_id INT UNSIGNED NOT NULL, expires_at BIGINT NOT NULL, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX (expires_at)) ENGINE=InnoDB`);
  await pool.query(`CREATE TABLE IF NOT EXISTS measurements (id CHAR(36) PRIMARY KEY, user_id INT UNSIGNED NOT NULL, date DATE NOT NULL, data_json LONGTEXT NOT NULL, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX (user_id, date)) ENGINE=InnoDB`);
  await pool.query(`CREATE TABLE IF NOT EXISTS workouts (id CHAR(36) PRIMARY KEY, user_id INT UNSIGNED NOT NULL, date DATE NOT NULL, exercise VARCHAR(100) NOT NULL, muscle_group VARCHAR(50) NOT NULL, sets INT NOT NULL, reps INT NOT NULL, weight DECIMAL(10,2) NOT NULL DEFAULT 0, notes VARCHAR(500) NOT NULL DEFAULT '', FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX (user_id, date)) ENGINE=InnoDB`);
  await pool.query(`CREATE TABLE IF NOT EXISTS routines (user_id INT UNSIGNED PRIMARY KEY, routine_json LONGTEXT NOT NULL, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB`);
  const email = String(process.env.ADMIN_EMAIL || '').trim().toLowerCase(); const password = String(process.env.ADMIN_PASSWORD || '');
  if (email && password.length >= 8) { const [rows] = await pool.query('SELECT id FROM users WHERE email = ?', [email]); if (rows.length) await pool.query("UPDATE users SET role = 'admin' WHERE id = ?", [rows[0].id]); else { const { salt, hash } = hashPassword(password); await pool.query("INSERT INTO users (email, password_hash, password_salt, role, profile_json) VALUES (?, ?, ?, 'admin', '{}')", [email, hash, salt]); } }
}
function hashPassword(password, salt = crypto.randomBytes(16).toString('hex')) { return { salt, hash: crypto.scryptSync(password, salt, 64).toString('hex') }; }
function safeEqual(left, right) { const a = Buffer.from(left, 'hex'); const b = Buffer.from(right, 'hex'); return a.length === b.length && crypto.timingSafeEqual(a, b); }
function parseProfile(value) { try { return JSON.parse(value || '{}'); } catch { return {}; } }
function publicUser(user) { return { id: user.id, email: user.email, role: user.role || 'user', profile: parseProfile(user.profile_json) }; }
function sessionToken(req) { return (req.headers.cookie || '').split(';').map(item => item.trim()).find(item => item.startsWith('formkurva_session='))?.split('=')[1]; }
async function sessionUser(req) { const token = sessionToken(req); if (!token) return null; const [rows] = await pool.query('SELECT users.*, sessions.id AS session_id FROM sessions JOIN users ON users.id = sessions.user_id WHERE sessions.id = ? AND sessions.expires_at > ?', [token, Date.now()]); return rows[0] || null; }
async function createSession(userId, res) { const token = crypto.randomBytes(32).toString('hex'); await pool.query('INSERT INTO sessions (id, user_id, expires_at) VALUES (?, ?, ?)', [token, userId, Date.now() + sessionDays * 86400000]); res.setHeader('Set-Cookie', `formkurva_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${sessionDays * 86400}${secureCookies ? '; Secure' : ''}`); }
async function requireUser(req, res, next) { try { req.user = await sessionUser(req); if (!req.user) return res.status(401).json({ error: 'Du måste vara inloggad.' }); next(); } catch (error) { next(error); } }
function requireAdmin(req, res, next) { if (req.user.role !== 'admin') return res.status(403).json({ error: 'Administratörsbehörighet krävs.' }); next(); }
function validMeasurement(data) { return data && /^\d{4}-\d{2}-\d{2}$/.test(data.date) && ['weight', 'waist', 'chest', 'arm', 'thigh', 'hip'].some(key => data[key] !== '' && data[key] !== undefined && Number(data[key]) >= 0); }

app.use(express.json({ limit: '8mb' }));
app.disable('x-powered-by');
app.use((req, res, next) => { res.setHeader('X-Content-Type-Options', 'nosniff'); res.setHeader('X-Frame-Options', 'SAMEORIGIN'); res.setHeader('Referrer-Policy', 'strict-origin-when-cross-origin'); res.setHeader('Permissions-Policy', 'camera=(), microphone=(), geolocation=()'); next(); });
app.use(express.static(path.join(__dirname), { index: 'MyHome.html' }));
setInterval(() => pool.query('DELETE FROM sessions WHERE expires_at <= ?', [Date.now()]).catch(console.error), 60 * 60 * 1000).unref();

app.get('/api/health', async (req, res, next) => { try { await pool.query('SELECT 1'); res.json({ ok: true, database: 'mariadb' }); } catch (error) { next(error); } });
app.get('/api/me', async (req, res, next) => { try { const user = await sessionUser(req); res.json({ user: user ? publicUser(user) : null }); } catch (error) { next(error); } });
app.post('/api/auth/register', async (req, res, next) => { try { const email = String(req.body.email || '').trim().toLowerCase(); const password = String(req.body.password || ''); if (!/^\S+@\S+\.\S+$/.test(email) || password.length < 8) return res.status(400).json({ error: 'Ange en giltig e-post och ett lösenord på minst 8 tecken.' }); const [existing] = await pool.query('SELECT id FROM users WHERE email = ?', [email]); if (existing.length) return res.status(409).json({ error: 'Det finns redan ett konto med den e-posten.' }); const { salt, hash } = hashPassword(password); const [result] = await pool.query("INSERT INTO users (email, password_hash, password_salt, profile_json) VALUES (?, ?, ?, '{}')", [email, hash, salt]); await createSession(result.insertId, res); const [rows] = await pool.query('SELECT * FROM users WHERE id = ?', [result.insertId]); res.status(201).json({ user: publicUser(rows[0]) }); } catch (error) { next(error); } });
app.post('/api/auth/login', async (req, res, next) => { try { const email = String(req.body.email || '').trim().toLowerCase(); const key = (req.ip || 'unknown') + ':' + email; const attempt = loginAttempts.get(key) || { count: 0, started: Date.now() }; if (Date.now() - attempt.started > loginWindowMs) { attempt.count = 0; attempt.started = Date.now(); } if (attempt.count >= 8) return res.status(429).json({ error: 'För många försök. Vänta 15 minuter och försök igen.' }); const [rows] = await pool.query('SELECT * FROM users WHERE email = ?', [email]); const user = rows[0]; if (!user || !safeEqual(hashPassword(String(req.body.password || ''), user.password_salt).hash, user.password_hash)) { attempt.count += 1; loginAttempts.set(key, attempt); return res.status(401).json({ error: 'E-posten eller lösenordet stämmer inte.' }); } loginAttempts.delete(key); await createSession(user.id, res); res.json({ user: publicUser(user) }); } catch (error) { next(error); } });
app.post('/api/auth/logout', requireUser, async (req, res, next) => { try { await pool.query('DELETE FROM sessions WHERE id = ?', [req.user.session_id]); res.setHeader('Set-Cookie', 'formkurva_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'); res.status(204).end(); } catch (error) { next(error); } });
app.post('/api/auth/change-password', requireUser, async (req, res, next) => { try { const current = String(req.body.currentPassword || ''); const nextPassword = String(req.body.newPassword || ''); if (nextPassword.length < 8) return res.status(400).json({ error: 'Det nya lösenordet måste vara minst 8 tecken.' }); if (!safeEqual(hashPassword(current, req.user.password_salt).hash, req.user.password_hash)) return res.status(401).json({ error: 'Det nuvarande lösenordet stämmer inte.' }); const { salt, hash } = hashPassword(nextPassword); await pool.query('UPDATE users SET password_hash = ?, password_salt = ? WHERE id = ?', [hash, salt, req.user.id]); await pool.query('DELETE FROM sessions WHERE user_id = ? AND id != ?', [req.user.id, req.user.session_id]); res.json({ ok: true }); } catch (error) { next(error); } });
app.get('/api/measurements', requireUser, async (req, res, next) => { try { const [rows] = await pool.query('SELECT id, date, data_json FROM measurements WHERE user_id = ? ORDER BY date DESC', [req.user.id]); res.json({ measurements: rows.map(row => ({ ...parseProfile(row.data_json), id: row.id, date: row.date.toISOString ? row.date.toISOString().slice(0, 10) : String(row.date) })) }); } catch (error) { next(error); } });
app.post('/api/measurements', requireUser, async (req, res, next) => { try { if (!validMeasurement(req.body)) return res.status(400).json({ error: 'Ange datum och minst ett mått.' }); const id = crypto.randomUUID(); const { date, ...data } = req.body; await pool.query('INSERT INTO measurements (id, user_id, date, data_json) VALUES (?, ?, ?, ?)', [id, req.user.id, date, JSON.stringify(data)]); res.status(201).json({ id, date, ...data }); } catch (error) { next(error); } });
app.put('/api/measurements/:id', requireUser, async (req, res, next) => { try { if (!validMeasurement(req.body)) return res.status(400).json({ error: 'Ange datum och minst ett mått.' }); const { date, ...data } = req.body; const [result] = await pool.query('UPDATE measurements SET date = ?, data_json = ? WHERE id = ? AND user_id = ?', [date, JSON.stringify(data), req.params.id, req.user.id]); if (!result.affectedRows) return res.status(404).json({ error: 'Mätningen hittades inte.' }); res.json({ id: req.params.id, date, ...data }); } catch (error) { next(error); } });
app.delete('/api/measurements/:id', requireUser, async (req, res, next) => { try { await pool.query('DELETE FROM measurements WHERE id = ? AND user_id = ?', [req.params.id, req.user.id]); res.status(204).end(); } catch (error) { next(error); } });
app.get('/api/workouts', requireUser, async (req, res, next) => { try { const [rows] = await pool.query('SELECT id, date, exercise, muscle_group, sets, reps, weight, notes FROM workouts WHERE user_id = ? ORDER BY date DESC', [req.user.id]); res.json({ workouts: rows.map(row => ({ ...row, date: row.date.toISOString ? row.date.toISOString().slice(0, 10) : String(row.date) })) }); } catch (error) { next(error); } });
app.post('/api/workouts', requireUser, async (req, res, next) => { try { const data = req.body || {}; if (!data.date || !data.exercise || !data.muscleGroup || Number(data.sets) < 1 || Number(data.reps) < 1 || Number(data.weight) < 0) return res.status(400).json({ error: 'Fyll i datum, övning, set, reps och vikt.' }); const workout = { id: crypto.randomUUID(), date: String(data.date), exercise: String(data.exercise).slice(0, 100), muscle_group: String(data.muscleGroup).slice(0, 50), sets: Number(data.sets), reps: Number(data.reps), weight: Number(data.weight), notes: String(data.notes || '').slice(0, 500) }; await pool.query('INSERT INTO workouts (id, user_id, date, exercise, muscle_group, sets, reps, weight, notes) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)', [workout.id, req.user.id, workout.date, workout.exercise, workout.muscle_group, workout.sets, workout.reps, workout.weight, workout.notes]); res.status(201).json(workout); } catch (error) { next(error); } });
app.delete('/api/workouts/:id', requireUser, async (req, res, next) => { try { await pool.query('DELETE FROM workouts WHERE id = ? AND user_id = ?', [req.params.id, req.user.id]); res.status(204).end(); } catch (error) { next(error); } });
app.get('/api/routine', requireUser, async (req, res, next) => { try { const [rows] = await pool.query('SELECT routine_json FROM routines WHERE user_id = ?', [req.user.id]); res.json({ routine: rows.length ? parseProfile(rows[0].routine_json) : { days: [] } }); } catch (error) { next(error); } });
app.put('/api/routine', requireUser, async (req, res, next) => { try { const routine = req.body && Array.isArray(req.body.days) ? { days: req.body.days.slice(0, 7).map(day => ({ name: String(day.name || 'Träningsdag').slice(0, 50), exercises: Array.isArray(day.exercises) ? day.exercises.map(exercise => String(exercise).slice(0, 100)).slice(0, 30) : [] })) } : { days: [] }; await pool.query('INSERT INTO routines (user_id, routine_json) VALUES (?, ?) ON DUPLICATE KEY UPDATE routine_json = VALUES(routine_json)', [req.user.id, JSON.stringify(routine)]); res.json({ routine }); } catch (error) { next(error); } });
app.put('/api/profile', requireUser, async (req, res, next) => { try { const profile = { ...req.body }; delete profile.email; await pool.query('UPDATE users SET profile_json = ? WHERE id = ?', [JSON.stringify(profile), req.user.id]); res.json({ profile }); } catch (error) { next(error); } });
app.delete('/api/account', requireUser, async (req, res, next) => { try { await pool.query('DELETE FROM users WHERE id = ?', [req.user.id]); res.setHeader('Set-Cookie', 'formkurva_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'); res.status(204).end(); } catch (error) { next(error); } });
app.get('/api/admin/stats', requireUser, requireAdmin, async (req, res, next) => { try { const [[users]] = await pool.query('SELECT COUNT(*) AS count FROM users'); const [[admins]] = await pool.query("SELECT COUNT(*) AS count FROM users WHERE role = 'admin'"); const [[measurements]] = await pool.query('SELECT COUNT(*) AS count FROM measurements'); res.json({ users: users.count, admins: admins.count, measurements: measurements.count }); } catch (error) { next(error); } });
app.get('/api/admin/users', requireUser, requireAdmin, async (req, res, next) => { try { const [rows] = await pool.query('SELECT users.id, users.email, users.role, users.created_at, COUNT(measurements.id) AS measurement_count FROM users LEFT JOIN measurements ON measurements.user_id = users.id GROUP BY users.id ORDER BY users.created_at ASC'); res.json({ users: rows }); } catch (error) { next(error); } });
app.patch('/api/admin/users/:id/role', requireUser, requireAdmin, async (req, res, next) => { try { const role = req.body.role === 'admin' ? 'admin' : req.body.role === 'user' ? 'user' : ''; const userId = Number(req.params.id); if (!role || !Number.isInteger(userId)) return res.status(400).json({ error: 'Ogiltig roll.' }); if (userId === req.user.id && role !== 'admin') return res.status(400).json({ error: 'Du kan inte ta bort adminrollen från dig själv.' }); const [[target]] = await pool.query('SELECT id, email, role FROM users WHERE id = ?', [userId]); if (!target) return res.status(404).json({ error: 'Kontot hittades inte.' }); if (target.role === 'admin' && role === 'user') { const [[count]] = await pool.query("SELECT COUNT(*) AS count FROM users WHERE role = 'admin'"); if (count.count <= 1) return res.status(400).json({ error: 'Det måste alltid finnas minst en administratör.' }); } await pool.query('UPDATE users SET role = ? WHERE id = ?', [role, userId]); res.json({ id: target.id, email: target.email, role }); } catch (error) { next(error); } });
+app.delete('/api/admin/users/:id', requireUser, requireAdmin, async (req, res, next) => { try { const userId = Number(req.params.id); if (userId === req.user.id) return res.status(400).json({ error: 'Du kan inte radera ditt eget admin-konto här.' }); const [[target]] = await pool.query('SELECT id, role FROM users WHERE id = ?', [userId]); if (!target) return res.status(404).json({ error: 'Kontot hittades inte.' }); if (target.role === 'admin') { const [[count]] = await pool.query("SELECT COUNT(*) AS count FROM users WHERE role = 'admin'"); if (count.count <= 1) return res.status(400).json({ error: 'Det måste alltid finnas minst en administratör.' }); } await pool.query('DELETE FROM users WHERE id = ?', [userId]); res.status(204).end(); } catch (error) { next(error); } });
+app.post('/api/admin/users/:id/logout', requireUser, requireAdmin, async (req, res, next) => { try { await pool.query('DELETE FROM sessions WHERE user_id = ?', [Number(req.params.id)]); res.status(204).end(); } catch (error) { next(error); } });
+app.use((error, req, res, next) => { console.error(error); res.status(500).json({ error: 'Ett oväntat serverfel uppstod.' }); });
+
+initDatabase().then(() => app.listen(port, () => console.log(`Formkurva kör på http://localhost:${port}`))).catch(error => { console.error('Databasen kunde inte startas:', error); process.exit(1); });
